services:
  postgres:
    image: postgres:18
    container_name: postgres_container_suivi
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend
    restart: unless-stopped

  app:
    image: bchamplon/suivi-mns-back:latest
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend
    restart: unless-stopped

  front:
    image: bchamplon/suivi-mns-front:latest
    ports:
      - "80:80"
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend: