spring.config.import=file:./.example.env[.properties],optional:file:./.env[.properties]

spring.application.name=SuiviMNS

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto = ${DDL_AUTO}
spring.jpa.show-sql=true

spring.sql.init.platform = ${SQL_FILE}

spring.sql.init.mode = ${SQL_INIT_MODE}

springdoc.api-docs.path=/api-docs

spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.jakarta.persistence.validation.mode=none

jwt.secret=${JWT_SECRET}